const {Variable} = require("./core")
const {} = require("./functions")
const Arr = require("./Arr")

let x = new Variable(Arr([[0,1,2], [3,4,5]]))
let y = x.reshape(6)
y.backward(true)
console.log(y)
console.log(x.grad)

x = new Variable(Arr([[1,2,3], [4,5,6]]))
y = x.transpose()
y.backward()
console.log(y)
console.log(x.grad)